name: Update Data

on:
  schedule:
    - cron:  '0 1 * * 1,5'
  workflow_dispatch:

env:
  AISWEB_API_KEY: ${{ secrets.AISWEB_API_KEY }}
  AISWEB_API_PASS: ${{ secrets.AISWEB_API_PASS }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    name: Update data run on Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies
      run: npm install

    - name: Run
      run: node run dev